# Generated by Django 4.0.3 on 2022-03-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_author_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='description',
        ),
    ]
