# Generated by Django 4.0.3 on 2022-03-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_remove_author_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
