# Generated by Django 4.0.3 on 2022-03-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_remove_post_images_remove_post_author_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
